const model = require('../models/adminInventoryModel');
const { hashPassword } = require('../utils/password');
function httpError(status, message) { const e = new Error(message); e.status = status; return e; }
function positiveId(value, name) { const n = Number(value); if (!Number.isInteger(n) || n <= 0) throw httpError(400, `${name} must be a positive integer`); return n; }
function requiredString(value, name, max = 255) { if (typeof value !== 'string' || !value.trim() || value.trim().length > max) throw httpError(400, `${name} is required and must be ${max} characters or fewer`); return value.trim(); }
async function list(query) { const threshold = query.threshold === undefined ? 10 : Number(query.threshold); if (!Number.isInteger(threshold) || threshold < 0) throw httpError(400, 'threshold must be a non-negative integer'); return { data: await model.listInventory({ lowStock: query.low_stock === 'true' || query.low_stock === '1', threshold, search: query.search?.trim() }) }; }
async function adjust(variantId, body, employeeId) { const stock = Number(body.stock_quantity); if (!Number.isInteger(stock) || stock < 0) throw httpError(400, 'stock_quantity must be a non-negative integer'); const reason = requiredString(body.reason, 'reason'); const variant = await model.adjustStock(positiveId(variantId, 'variantId'), positiveId(employeeId, 'employeeId'), stock, reason); return variant; }
async function createEmployee(body) { const email = requiredString(body.email, 'email', 100).toLowerCase(); const password = requiredString(body.password, 'password', 200); if (password.length < 8) throw httpError(400, 'password must be at least 8 characters'); const firstName = requiredString(body.first_name, 'first_name', 50); const lastName = requiredString(body.last_name, 'last_name', 50); const phone = body.phone ? requiredString(body.phone, 'phone', 20) : null; return model.createEmployee({ email, passwordHash: await hashPassword(password), firstName, lastName, phone }); }
module.exports = { list, adjust, createEmployee, listEmployees: model.listEmployees };
