-- 04_products.sql: Seed 40 products, variants, and BYTEA images
-- Written by Member C (Backend - Products)

--------------------------------------------------------------------------------
-- 1. Insert 40 Products
--------------------------------------------------------------------------------
INSERT INTO products (product_name, brand, description, base_sku, is_active) VALUES
  ('OmniCharge 65W GaN Fast Charger', 'PowerPulse', 'Ultra-compact 65W GaN wall charger with 2x USB-C PD and 1x USB-A ports for multi-device charging.', 'ELC-001', true),
  ('StreamDeck Creator Hub', 'NovaTech', '15 customizable LCD keys to trigger studio actions, control audio, launch apps, and automate workflows.', 'ELC-002', true),
  ('ViewMaster 4K Action Camera', 'ViewMaster', 'Rugged waterproof 4K60fps camera with advanced stabilization, front color preview, and rear touchscreen.', 'ELC-003', true),
  ('SmartTrack GPS Tag 4-Pack', 'Aura', 'Ultra-wideband smart finder tags with replaceable coin batteries and global community tracking network.', 'ELC-004', true),
  ('Lumina Pro 5G', 'Lumina', 'Flagship 6.7-inch AMOLED 120Hz smartphone with pro-grade triple camera and 5000mAh battery.', 'SPH-001', true),
  ('Lumina Ultra Max', 'Lumina', 'Top-tier productivity smartphone featuring integrated active stylus and 100x Space Zoom sensor.', 'SPH-002', true),
  ('Aura Mini 5G', 'Aura', 'Ergonomic 5.8-inch edge-to-edge compact smartphone offering pure one-handed convenience.', 'SPH-003', true),
  ('Vortex Fold Z', 'Vortex', 'Seamless inward-folding flexible AMOLED display smartphone with IPX8 water resistance.', 'SPH-004', true),
  ('ZenithBook Pro 15', 'Zenith', '15.6-inch 3K OLED creator laptop powered by high-efficiency 14-core processor and glass touchpad.', 'LAP-001', true),
  ('ZenithBook Air 13', 'Zenith', 'Featherlight 2.1 lb ultrabook with silent fanless thermal design and 18 hours of real-world battery life.', 'LAP-002', true),
  ('Titan Gaming Blade 16', 'Titan', 'Heavy-duty esports laptop boasting 240Hz QHD display, per-key RGB, and vapor chamber liquid cooling.', 'LAP-003', true),
  ('NovaFlex 2-in-1 Touch', 'NovaTech', 'Flexible 360-degree convertible laptop supporting touch gestures and magnetic active pressure stylus.', 'LAP-004', true),
  ('Sonus QuietComfort Elite', 'Sonus', 'Engineered over-ear headphones with adaptive active noise cancellation and personalized sound profile.', 'AUD-001', true),
  ('Pulse True Wireless Earbuds', 'Sonus', 'Lightweight water-resistant in-ear earbuds with dual beamforming microphones and Qi wireless charging.', 'AUD-002', true),
  ('BassBoom 360 Bluetooth Speaker', 'BassBoom', 'IP67 dustproof and waterproof cylindrical speaker delivering punchy 360-degree audio and bass radiators.', 'AUD-003', true),
  ('StudioMaster Reference Monitor Pair', 'Sonus', 'Precision near-field active studio monitors with Kevlar low-frequency drivers and acoustic space switches.', 'AUD-004', true),
  ('PureAir HEPA Smart Purifier', 'PureHome', 'Hospital-grade H13 True HEPA filter capturing 99.97% of airborne dust, pollen, and allergens with smart app control.', 'HAP-001', true),
  ('BreezeCool Ceramic Tower Heater', 'PureHome', 'Widespread oscillating oscillating ceramic heating element with digital thermostat and auto-shutoff tip protection.', 'HAP-002', true),
  ('AeroMist Ultrasonic Humidifier', 'PureHome', '4-Liter cool mist humidifier with whisper-quiet ultrasonic operation and aroma diffuser compartment.', 'HAP-003', true),
  ('DeconDehumidifier 50-Pint', 'AirPro', 'Energy Star rated high-capacity dehumidifier for basements and large living spaces with continuous pump drain.', 'HAP-004', true),
  ('ChefAir Digital 6-Quart Air Fryer', 'ChefCraft', 'Rapid 360-degree convection heat air fryer with nonstick ceramic basket and 8 preset cooking functions.', 'KIT-001', true),
  ('BaristaTouch Espresso Machine', 'BaristaPro', 'All-in-one espresso maker with built-in stainless conical grinder, 15-bar Italian pump, and microfoam wand.', 'KIT-002', true),
  ('PowerBlend 1200W Blender', 'ChefCraft', 'Commercial-grade 1200-watt blender with stainless 6-point extraction blades and shatterproof 64oz jar.', 'KIT-003', true),
  ('SmartSous Precision Immersion Cooker', 'ChefCraft', 'Accurate temperature sous vide immersion circulator with WiFi connectivity and clear LED status display.', 'KIT-004', true),
  ('RoboVac Ultra LiDAR Robot Vacuum', 'CleanBot', 'Smart laser LiDAR mapping vacuum with 4000Pa suction power, carpet boost, and auto-dust empty dock.', 'CLN-001', true),
  ('Cyclone Cordless Stick Vacuum', 'CleanBot', 'Lightweight cordless vacuum with multi-surface motorized roller brush and 50-minute runtime removable battery.', 'CLN-002', true),
  ('HydroSteam Sanitizing Floor Mop', 'SteamClean', 'Chemical-free steam mop heating in 30 seconds to sanitize hard wood, tile, and laminate flooring.', 'CLN-003', true),
  ('DusterPro Handheld Car Vacuum', 'CleanBot', 'Compact high-power handheld vacuum cleaner with washable HEPA filter and USB-C fast charging.', 'CLN-004', true),
  ('BrightBuy Urban Commuter Backpack', 'ApexGear', 'Weatherproof 24L commuter backpack with padded 16-inch laptop compartment and hidden passport pocket.', 'APP-001', true),
  ('Apex All-Weather Travel Duffel', 'ApexGear', 'Heavy-duty TPU coated water-resistant 45L duffel bag with convertible backpack shoulder straps.', 'APP-002', true),
  ('Merino Wool Thermal Beanie', 'ApexGear', 'Breathable cold-weather knit beanie constructed from 100% fine spun Merino wool.', 'APP-003', true),
  ('Polarized Sports Sunglasses', 'ApexGear', 'UV400 polarized athletic sunglasses with lightweight TR90 memory frames and hydrophobic lens coating.', 'APP-004', true),
  ('Classic Oxford Cotton Button-Down', 'Heritage', 'Classic tailored fit long-sleeve oxford shirt crafted from 100% combed breathable cotton.', 'MCL-001', true),
  ('Tech Stretch Chino Trousers', 'Heritage', 'Versatile smart-casual trousers featuring comfortable 4-way stretch fabric and water-repellent finish.', 'MCL-002', true),
  ('Merino Wool Crewneck Sweater', 'Heritage', 'Ribbed cuffs and hem knit from pure lightweight Australian Merino wool for effortless layering.', 'MCL-003', true),
  ('Lightweight Windbreaker Running Jacket', 'PeakAthletics', 'Wind-resistant athletic jacket with underarm ventilation perforations and 360-degree reflective accents.', 'MCL-004', true),
  ('Tailored Silk-Blend Blouse', 'Elegance', 'Soft silk-blend blouse featuring concealed button placket and flattering fluid silhouette.', 'WCL-001', true),
  ('High-Rise Stretch Skinny Denim', 'DenimCo', 'Flattering high-rise fit skinny jeans engineered with advanced shape-retention recovery denim.', 'WCL-002', true),
  ('Cashmere Open-Front Cardigan', 'Elegance', 'Sumptuously soft 100% Mongolian cashmere relaxed cardigan with dropped shoulders and ribbed patch pockets.', 'WCL-003', true),
  ('Breathable Flex Yoga Leggings', 'PeakAthletics', 'High-waisted compression athletic leggings made from moisture-wicking four-way stretch fabric with side pockets.', 'WCL-004', true);

--------------------------------------------------------------------------------
-- 2. Insert Product Variants (Linked by base_sku)
--------------------------------------------------------------------------------
INSERT INTO product_variants (product_id, variant_sku, variant_name, price, stock_quantity, is_active) VALUES
  ((SELECT product_id FROM products WHERE base_sku = 'ELC-001'), 'ELC-001-WHT', 'Glacier White', 39.99, 75, true),
  ((SELECT product_id FROM products WHERE base_sku = 'ELC-001'), 'ELC-001-BLK', 'Midnight Black', 39.99, 50, true),
  ((SELECT product_id FROM products WHERE base_sku = 'ELC-002'), 'ELC-002-STD', 'Standard Matte Black', 149.99, 28, true),
  ((SELECT product_id FROM products WHERE base_sku = 'ELC-003'), 'ELC-003-STD', 'Standard Pack', 249.00, 19, true),
  ((SELECT product_id FROM products WHERE base_sku = 'ELC-003'), 'ELC-003-ADV', 'Adventure Bundle', 299.00, 3, true),
  ((SELECT product_id FROM products WHERE base_sku = 'ELC-004'), 'ELC-004-1PK', 'Single Tag White', 29.99, 100, true),
  ((SELECT product_id FROM products WHERE base_sku = 'ELC-004'), 'ELC-004-4PK', '4-Pack Multipack', 89.99, 40, true),
  ((SELECT product_id FROM products WHERE base_sku = 'SPH-001'), 'SPH-001-BLK-128', 'Space Black / 128GB', 799.00, 45, true),
  ((SELECT product_id FROM products WHERE base_sku = 'SPH-001'), 'SPH-001-SLV-256', 'Titanium Silver / 256GB', 899.00, 20, true),
  ((SELECT product_id FROM products WHERE base_sku = 'SPH-002'), 'SPH-002-GLD-256', 'Champagne Gold / 256GB', 1099.00, 15, true),
  ((SELECT product_id FROM products WHERE base_sku = 'SPH-002'), 'SPH-002-BLK-512', 'Phantom Black / 512GB', 1249.00, 2, true),
  ((SELECT product_id FROM products WHERE base_sku = 'SPH-003'), 'SPH-003-BLU-64', 'Sky Blue / 64GB', 499.00, 30, true),
  ((SELECT product_id FROM products WHERE base_sku = 'SPH-003'), 'SPH-003-GRN-128', 'Sage Green / 128GB', 549.00, 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'SPH-004'), 'SPH-004-BLK-256', 'Obsidian Black / 256GB', 1399.00, 12, true),
  ((SELECT product_id FROM products WHERE base_sku = 'SPH-004'), 'SPH-004-SLV-512', 'Mirror Silver / 512GB', 1599.00, 5, true),
  ((SELECT product_id FROM products WHERE base_sku = 'LAP-001'), 'LAP-001-16G-512', '16GB RAM / 512GB SSD', 1299.00, 25, true),
  ((SELECT product_id FROM products WHERE base_sku = 'LAP-001'), 'LAP-001-32G-1TB', '32GB RAM / 1TB SSD', 1699.00, 10, true),
  ((SELECT product_id FROM products WHERE base_sku = 'LAP-002'), 'LAP-002-8G-256', '8GB RAM / 256GB SSD', 899.00, 35, true),
  ((SELECT product_id FROM products WHERE base_sku = 'LAP-002'), 'LAP-002-16G-512', '16GB RAM / 512GB SSD', 1099.00, 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'LAP-003'), 'LAP-003-16G-1TB', 'RTX 4070 / 16GB / 1TB', 1799.00, 18, true),
  ((SELECT product_id FROM products WHERE base_sku = 'LAP-003'), 'LAP-003-32G-2TB', 'RTX 4080 / 32GB / 2TB', 2399.00, 4, true),
  ((SELECT product_id FROM products WHERE base_sku = 'LAP-004'), 'LAP-004-8G-512', '8GB RAM / 512GB SSD', 749.00, 22, true),
  ((SELECT product_id FROM products WHERE base_sku = 'LAP-004'), 'LAP-004-16G-1TB', '16GB RAM / 1TB SSD', 949.00, 14, true),
  ((SELECT product_id FROM products WHERE base_sku = 'AUD-001'), 'AUD-001-BLK', 'Matte Black', 299.00, 50, true),
  ((SELECT product_id FROM products WHERE base_sku = 'AUD-001'), 'AUD-001-WHT', 'Ivory White', 299.00, 3, true),
  ((SELECT product_id FROM products WHERE base_sku = 'AUD-002'), 'AUD-002-BLK', 'Graphite Black', 149.00, 60, true),
  ((SELECT product_id FROM products WHERE base_sku = 'AUD-002'), 'AUD-002-BLU', 'Deep Navy', 149.00, 40, true),
  ((SELECT product_id FROM products WHERE base_sku = 'AUD-003'), 'AUD-003-BLK', 'Charcoal Black', 99.00, 40, true),
  ((SELECT product_id FROM products WHERE base_sku = 'AUD-003'), 'AUD-003-RED', 'Crimson Red', 99.00, 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'AUD-004'), 'AUD-004-PAIR', 'Matched Studio Pair', 399.00, 15, true),
  ((SELECT product_id FROM products WHERE base_sku = 'HAP-001'), 'HAP-001-WHT', 'Glacier White', 179.99, 32, true),
  ((SELECT product_id FROM products WHERE base_sku = 'HAP-001'), 'HAP-001-SLV', 'Brushed Silver', 199.99, 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'HAP-002'), 'HAP-002-BLK', 'Matte Black', 89.99, 24, true),
  ((SELECT product_id FROM products WHERE base_sku = 'HAP-003'), 'HAP-003-4L', '4L Standard White', 59.99, 45, true),
  ((SELECT product_id FROM products WHERE base_sku = 'HAP-004'), 'HAP-004-WHT', 'Arctic White', 229.00, 16, true),
  ((SELECT product_id FROM products WHERE base_sku = 'KIT-001'), 'KIT-001-BLK', 'Onyx Black', 99.99, 55, true),
  ((SELECT product_id FROM products WHERE base_sku = 'KIT-001'), 'KIT-001-SS', 'Stainless Steel', 119.99, 20, true),
  ((SELECT product_id FROM products WHERE base_sku = 'KIT-002'), 'KIT-002-SS', 'Brushed Stainless', 549.99, 12, true),
  ((SELECT product_id FROM products WHERE base_sku = 'KIT-002'), 'KIT-002-BLK', 'Cast Iron Black', 549.99, 4, true),
  ((SELECT product_id FROM products WHERE base_sku = 'KIT-003'), 'KIT-003-GRY', 'Slate Gray', 79.99, 38, true),
  ((SELECT product_id FROM products WHERE base_sku = 'KIT-004'), 'KIT-004-BLK', 'Stainless & Black', 129.99, 26, true),
  ((SELECT product_id FROM products WHERE base_sku = 'CLN-001'), 'CLN-001-WHT', 'Pearl White', 399.00, 22, true),
  ((SELECT product_id FROM products WHERE base_sku = 'CLN-001'), 'CLN-001-BLK', 'Midnight Black', 399.00, 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'CLN-002'), 'CLN-002-BLU', 'Cobalt Blue', 199.99, 35, true),
  ((SELECT product_id FROM products WHERE base_sku = 'CLN-002'), 'CLN-002-RED', 'Ruby Red', 199.99, 18, true),
  ((SELECT product_id FROM products WHERE base_sku = 'CLN-003'), 'CLN-003-WHT', 'White & Cyan', 69.99, 42, true),
  ((SELECT product_id FROM products WHERE base_sku = 'CLN-004'), 'CLN-004-GRY', 'Space Gray', 49.99, 50, true),
  ((SELECT product_id FROM products WHERE base_sku = 'APP-001'), 'APP-001-BLK', 'Jet Black / 24L', 69.00, 60, true),
  ((SELECT product_id FROM products WHERE base_sku = 'APP-001'), 'APP-001-GRY', 'Slate Heather / 24L', 69.00, 3, true),
  ((SELECT product_id FROM products WHERE base_sku = 'APP-002'), 'APP-002-OLV', 'Olive Green / 45L', 89.00, 25, true),
  ((SELECT product_id FROM products WHERE base_sku = 'APP-003'), 'APP-003-BLK', 'Classic Black', 24.99, 80, true),
  ((SELECT product_id FROM products WHERE base_sku = 'APP-003'), 'APP-003-NVY', 'Heather Navy', 24.99, 65, true),
  ((SELECT product_id FROM products WHERE base_sku = 'APP-004'), 'APP-004-BLK', 'Black Frame / Smoke Lens', 45.00, 40, true),
  ((SELECT product_id FROM products WHERE base_sku = 'APP-004'), 'APP-004-TOR', 'Tortoise / Bronze Lens', 45.00, 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'MCL-001'), 'MCL-001-WHT-M', 'White / Size M', 49.50, 40, true),
  ((SELECT product_id FROM products WHERE base_sku = 'MCL-001'), 'MCL-001-BLU-L', 'Sky Blue / Size L', 49.50, 35, true),
  ((SELECT product_id FROM products WHERE base_sku = 'MCL-002'), 'MCL-002-KHK-32', 'Khaki / 32W 32L', 59.50, 30, true),
  ((SELECT product_id FROM products WHERE base_sku = 'MCL-002'), 'MCL-002-NVY-34', 'Navy / 34W 32L', 59.50, 2, true),
  ((SELECT product_id FROM products WHERE base_sku = 'MCL-003'), 'MCL-003-CHL-M', 'Charcoal / Size M', 79.00, 28, true),
  ((SELECT product_id FROM products WHERE base_sku = 'MCL-003'), 'MCL-003-CAM-L', 'Camel Tan / Size L', 79.00, 15, true),
  ((SELECT product_id FROM products WHERE base_sku = 'MCL-004'), 'MCL-004-BLK-L', 'Stealth Black / Size L', 65.00, 32, true),
  ((SELECT product_id FROM products WHERE base_sku = 'MCL-004'), 'MCL-004-BLU-M', 'Electric Blue / Size M', 65.00, 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'WCL-001'), 'WCL-001-CRM-S', 'Cream Ivory / Size S', 64.00, 30, true),
  ((SELECT product_id FROM products WHERE base_sku = 'WCL-001'), 'WCL-001-BLS-M', 'Blush Pink / Size M', 64.00, 25, true),
  ((SELECT product_id FROM products WHERE base_sku = 'WCL-002'), 'WCL-002-IND-28', 'Dark Indigo / Size 28', 68.00, 40, true),
  ((SELECT product_id FROM products WHERE base_sku = 'WCL-002'), 'WCL-002-BLK-30', 'Washed Black / Size 30', 68.00, 4, true),
  ((SELECT product_id FROM products WHERE base_sku = 'WCL-003'), 'WCL-003-OAT-M', 'Oatmeal Heather / Size M', 119.00, 20, true),
  ((SELECT product_id FROM products WHERE base_sku = 'WCL-003'), 'WCL-003-GRY-L', 'Dove Gray / Size L', 119.00, 15, true),
  ((SELECT product_id FROM products WHERE base_sku = 'WCL-004'), 'WCL-004-BLK-S', 'Classic Black / Size S', 48.00, 55, true),
  ((SELECT product_id FROM products WHERE base_sku = 'WCL-004'), 'WCL-004-SGE-M', 'Sage Green / Size M', 48.00, 0, true);

--------------------------------------------------------------------------------
-- 3. Insert Product Images as BYTEA (Linked by base_sku)
--------------------------------------------------------------------------------
INSERT INTO product_images (product_id, image_data, sort_order, is_primary) VALUES
  ((SELECT product_id FROM products WHERE base_sku = 'ELC-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'ELC-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64'), 1, false),
  ((SELECT product_id FROM products WHERE base_sku = 'ELC-002'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'ELC-003'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'ELC-003'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 1, false),
  ((SELECT product_id FROM products WHERE base_sku = 'ELC-004'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWPifDwAEeQGAm7eJwgAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'SPH-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'SPH-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 1, false),
  ((SELECT product_id FROM products WHERE base_sku = 'SPH-002'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'SPH-003'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'SPH-004'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'LAP-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'LAP-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 1, false),
  ((SELECT product_id FROM products WHERE base_sku = 'LAP-002'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'LAP-003'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'LAP-003'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 1, false),
  ((SELECT product_id FROM products WHERE base_sku = 'LAP-004'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'AUD-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'AUD-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 1, false),
  ((SELECT product_id FROM products WHERE base_sku = 'AUD-002'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'AUD-003'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'AUD-004'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'HAP-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWPifDwAEeQGAm7eJwgAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'HAP-002'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'HAP-003'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'HAP-004'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'KIT-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'KIT-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64'), 1, false),
  ((SELECT product_id FROM products WHERE base_sku = 'KIT-002'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'KIT-002'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 1, false),
  ((SELECT product_id FROM products WHERE base_sku = 'KIT-003'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'KIT-004'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'CLN-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'CLN-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWPifDwAEeQGAm7eJwgAAAABJRU5ErkJggg==', 'base64'), 1, false),
  ((SELECT product_id FROM products WHERE base_sku = 'CLN-002'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'CLN-003'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'CLN-004'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'APP-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'APP-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 1, false),
  ((SELECT product_id FROM products WHERE base_sku = 'APP-002'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWPifDwAEeQGAm7eJwgAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'APP-003'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'APP-004'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'MCL-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'MCL-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 1, false),
  ((SELECT product_id FROM products WHERE base_sku = 'MCL-002'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'MCL-003'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'MCL-004'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'WCL-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'WCL-001'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 1, false),
  ((SELECT product_id FROM products WHERE base_sku = 'WCL-002'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'WCL-003'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==', 'base64'), 0, true),
  ((SELECT product_id FROM products WHERE base_sku = 'WCL-004'), decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWPifDwAEeQGAm7eJwgAAAABJRU5ErkJggg==', 'base64'), 0, true);
