-- Link Products to Categories
WITH product_cats(sku, cat) AS (
    VALUES
    ('ELC-001', 'Electronics'),
    ('ELC-002', 'Electronics'),
    ('ELC-003', 'Electronics'),
    ('ELC-004', 'Electronics'),
    ('SPH-001', 'Smartphones'),
    ('SPH-002', 'Smartphones'),
    ('SPH-003', 'Smartphones'),
    ('SPH-004', 'Smartphones'),
    ('LAP-001', 'Laptops'),
    ('LAP-002', 'Laptops'),
    ('LAP-003', 'Laptops'),
    ('LAP-004', 'Laptops'),
    ('AUD-001', 'Audio'),
    ('AUD-002', 'Audio'),
    ('AUD-003', 'Audio'),
    ('AUD-004', 'Audio'),
    ('HAP-001', 'Home Appliances'),
    ('HAP-002', 'Home Appliances'),
    ('HAP-003', 'Home Appliances'),
    ('HAP-004', 'Home Appliances'),
    ('KIT-001', 'Kitchen'),
    ('KIT-002', 'Kitchen'),
    ('KIT-003', 'Kitchen'),
    ('KIT-004', 'Kitchen'),
    ('CLN-001', 'Cleaning'),
    ('CLN-002', 'Cleaning'),
    ('CLN-003', 'Cleaning'),
    ('CLN-004', 'Cleaning'),
    ('APP-001', 'Apparel'),
    ('APP-002', 'Apparel'),
    ('APP-003', 'Apparel'),
    ('APP-004', 'Apparel'),
    ('MCL-001', 'Men''s Clothing'),
    ('MCL-002', 'Men''s Clothing'),
    ('MCL-003', 'Men''s Clothing'),
    ('MCL-004', 'Men''s Clothing'),
    ('WCL-001', 'Women''s Clothing'),
    ('WCL-002', 'Women''s Clothing'),
    ('WCL-003', 'Women''s Clothing'),
    ('WCL-004', 'Women''s Clothing')
)
INSERT INTO product_categories (product_id, category_id)
SELECT p.product_id, c.category_id
FROM product_cats pc
JOIN products p ON p.base_sku = pc.sku
JOIN categories c ON c.category_name = pc.cat;

-- Variant Attributes
WITH var_attrs(sku, attr, val) AS (
    VALUES
    ('ELC-001-WHT', 'Color', 'Glacier White'),
    ('ELC-001-BLK', 'Color', 'Midnight Black'),
    ('ELC-002-STD', 'Color', 'Standard Matte Black'),
    ('ELC-003-STD', 'Color', 'Standard Pack'),
    ('ELC-003-ADV', 'Color', 'Adventure Bundle'),
    ('ELC-004-1PK', 'Color', 'Single Tag White'),
    ('ELC-004-4PK', 'Color', '4-Pack Multipack'),
    ('SPH-001-BLK-128', 'Color', 'Space Black'),
    ('SPH-001-BLK-128', 'Storage', '128GB'),
    ('SPH-001-SLV-256', 'Color', 'Titanium Silver'),
    ('SPH-001-SLV-256', 'Storage', '256GB'),
    ('SPH-002-GLD-256', 'Color', 'Champagne Gold'),
    ('SPH-002-GLD-256', 'Storage', '256GB'),
    ('SPH-002-BLK-512', 'Color', 'Phantom Black'),
    ('SPH-002-BLK-512', 'Storage', '512GB'),
    ('SPH-003-BLU-64', 'Color', 'Sky Blue'),
    ('SPH-003-BLU-64', 'Storage', '64GB'),
    ('SPH-003-GRN-128', 'Color', 'Sage Green'),
    ('SPH-003-GRN-128', 'Storage', '128GB'),
    ('SPH-004-BLK-256', 'Color', 'Obsidian Black'),
    ('SPH-004-BLK-256', 'Storage', '256GB'),
    ('SPH-004-SLV-512', 'Color', 'Mirror Silver'),
    ('SPH-004-SLV-512', 'Storage', '512GB'),
    ('LAP-001-16G-512', 'RAM', '16GB'),
    ('LAP-001-16G-512', 'Storage', '512GB SSD'),
    ('LAP-001-32G-1TB', 'RAM', '32GB'),
    ('LAP-001-32G-1TB', 'Storage', '1TB SSD'),
    ('LAP-002-8G-256', 'RAM', '8GB'),
    ('LAP-002-8G-256', 'Storage', '256GB SSD'),
    ('LAP-002-16G-512', 'RAM', '16GB'),
    ('LAP-002-16G-512', 'Storage', '512GB SSD'),
    ('LAP-003-16G-1TB', 'RAM', '16GB'),
    ('LAP-003-16G-1TB', 'Storage', '1TB SSD'),
    ('LAP-003-32G-2TB', 'RAM', '32GB'),
    ('LAP-003-32G-2TB', 'Storage', '2TB SSD'),
    ('LAP-004-8G-512', 'RAM', '8GB'),
    ('LAP-004-8G-512', 'Storage', '512GB SSD'),
    ('LAP-004-16G-1TB', 'RAM', '16GB'),
    ('LAP-004-16G-1TB', 'Storage', '1TB SSD'),
    ('AUD-001-BLK', 'Color', 'Matte Black'),
    ('AUD-001-WHT', 'Color', 'Ivory White'),
    ('AUD-002-BLK', 'Color', 'Graphite Black'),
    ('AUD-002-BLU', 'Color', 'Deep Navy'),
    ('AUD-003-BLK', 'Color', 'Charcoal Black'),
    ('AUD-003-RED', 'Color', 'Crimson Red'),
    ('AUD-004-PAIR', 'Color', 'Matched Studio Pair'),
    ('HAP-001-WHT', 'Color', 'Glacier White'),
    ('HAP-001-SLV', 'Color', 'Brushed Silver'),
    ('HAP-002-BLK', 'Color', 'Matte Black'),
    ('HAP-003-4L', 'Size', '4L'),
    ('HAP-004-WHT', 'Color', 'Arctic White'),
    ('KIT-001-BLK', 'Color', 'Onyx Black'),
    ('KIT-001-SS', 'Color', 'Stainless Steel'),
    ('KIT-002-SS', 'Color', 'Brushed Stainless'),
    ('KIT-002-BLK', 'Color', 'Cast Iron Black'),
    ('KIT-003-GRY', 'Color', 'Slate Gray'),
    ('KIT-004-BLK', 'Color', 'Stainless & Black'),
    ('CLN-001-WHT', 'Color', 'Pearl White'),
    ('CLN-001-BLK', 'Color', 'Midnight Black'),
    ('CLN-002-BLU', 'Color', 'Cobalt Blue'),
    ('CLN-002-RED', 'Color', 'Ruby Red'),
    ('CLN-003-WHT', 'Color', 'White & Cyan'),
    ('CLN-004-GRY', 'Color', 'Space Gray'),
    ('APP-001-BLK', 'Color', 'Jet Black'),
    ('APP-001-BLK', 'Size', '24L'),
    ('APP-001-GRY', 'Color', 'Slate Heather'),
    ('APP-001-GRY', 'Size', '24L'),
    ('APP-002-OLV', 'Color', 'Olive Green'),
    ('APP-002-OLV', 'Size', '45L'),
    ('APP-003-BLK', 'Color', 'Classic Black'),
    ('APP-003-NVY', 'Color', 'Heather Navy'),
    ('APP-004-BLK', 'Color', 'Black Frame'),
    ('APP-004-TOR', 'Color', 'Tortoise'),
    ('MCL-001-WHT-M', 'Color', 'White'),
    ('MCL-001-WHT-M', 'Size', 'M'),
    ('MCL-001-BLU-L', 'Color', 'Sky Blue'),
    ('MCL-001-BLU-L', 'Size', 'L'),
    ('MCL-002-KHK-32', 'Color', 'Khaki'),
    ('MCL-002-KHK-32', 'Size', '32W 32L'),
    ('MCL-002-NVY-34', 'Color', 'Navy'),
    ('MCL-002-NVY-34', 'Size', '34W 32L'),
    ('MCL-003-CHL-M', 'Color', 'Charcoal'),
    ('MCL-003-CHL-M', 'Size', 'M'),
    ('MCL-003-CAM-L', 'Color', 'Camel Tan'),
    ('MCL-003-CAM-L', 'Size', 'L'),
    ('MCL-004-BLK-L', 'Color', 'Stealth Black'),
    ('MCL-004-BLK-L', 'Size', 'L'),
    ('MCL-004-BLU-M', 'Color', 'Electric Blue'),
    ('MCL-004-BLU-M', 'Size', 'M'),
    ('WCL-001-CRM-S', 'Color', 'Cream Ivory'),
    ('WCL-001-CRM-S', 'Size', 'S'),
    ('WCL-001-BLS-M', 'Color', 'Blush Pink'),
    ('WCL-001-BLS-M', 'Size', 'M'),
    ('WCL-002-IND-28', 'Color', 'Dark Indigo'),
    ('WCL-002-IND-28', 'Size', '28'),
    ('WCL-002-BLK-30', 'Color', 'Washed Black'),
    ('WCL-002-BLK-30', 'Size', '30'),
    ('WCL-003-OAT-M', 'Color', 'Oatmeal Heather'),
    ('WCL-003-OAT-M', 'Size', 'M'),
    ('WCL-003-GRY-L', 'Color', 'Dove Gray'),
    ('WCL-003-GRY-L', 'Size', 'L'),
    ('WCL-004-BLK-S', 'Color', 'Classic Black'),
    ('WCL-004-BLK-S', 'Size', 'S'),
    ('WCL-004-SGE-M', 'Color', 'Sage Green'),
    ('WCL-004-SGE-M', 'Size', 'M')
)
INSERT INTO variant_attribute_values (variant_id, attribute_id, attribute_value)
SELECT pv.variant_id, va.attribute_id, va_val.val
FROM var_attrs va_val
JOIN product_variants pv ON pv.variant_sku = va_val.sku
JOIN variant_attributes va ON va.attribute_name = va_val.attr;
